name: proveCI
on:
  push:
    branches:
      - develop
env:
  container: externalexte/bbatch_prove
jobs:
  bbatch-prove:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Source Files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **.mch

      - name: pull the container
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          docker pull ${{env.container}}
      - name: Prove Changed Files!
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          docker run -v ${{ github.workspace }}:/repository ${{env.container}} ${{steps.changed-files.outputs.all_changed_files}}
